// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/game/spectator/{user_id}/{game_id}": {
            "post": {
                "description": "Данный метод позволяет пользователю начать просмотр игры с заданным идентификатором игры.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Начать просмотр текущей игры как зритель",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Идентификатор игры",
                        "name": "game_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное подключение к игре",
                        "schema": {
                            "$ref": "#/definitions/models.AddSpectatorResponse"
                        }
                    },
                    "400": {
                        "description": "Игра больше не существует (завершена) или некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.AddSpectatorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/models.AddSpectatorResponse"
                        }
                    }
                }
            }
        },
        "/game/{id}": {
            "post": {
                "description": "Данный метод позволяет пользователю начать поиск игры с заданным списком метатем.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Начать поиск игры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Список метатем",
                        "name": "metathemes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddGameSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное начало поиска игры",
                        "schema": {
                            "$ref": "#/definitions/models.AddGameSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса или пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/models.AddGameSearchResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/models.AddGameSearchResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Данный метод позволяет пользователю остановить поиск игры.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Остановить поиск игры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная остановка поиска игры",
                        "schema": {
                            "$ref": "#/definitions/models.StopGameSearchResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/models.StopGameSearchResponse"
                        }
                    }
                }
            }
        },
        "/rooms/create": {
            "post": {
                "description": "Создает новую игровую комнату с заданным именем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Создание новой игровой комнаты",
                "parameters": [
                    {
                        "description": "Информация о комнате",
                        "name": "room",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateRoomResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateRoomResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateRoomResponse"
                        }
                    }
                }
            }
        },
        "/rooms/{room_id}/players": {
            "get": {
                "description": "Возвращает список игроков в указанной игровой комнате",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Получение информации об игроках в комнате",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор комнаты",
                        "name": "room_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PlayersInRoomResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.PlayersInRoomResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.PlayersInRoomResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет пользователя в указанную игровую комнату",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Добавление игрока в комнату",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор комнаты",
                        "name": "room_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация об игроке",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AddPlayerToRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddPlayerToRoomResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddPlayerToRoomResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddPlayerToRoomResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddPlayerToRoomResponse"
                        }
                    }
                }
            }
        },
        "/theme": {
            "post": {
                "description": "Данный метод позволяет предложить новую тему/метатему в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "theme"
                ],
                "summary": "Предложение новой темы/метатемы",
                "parameters": [
                    {
                        "description": "Предлагаемая тема",
                        "name": "theme",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddThemeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Тема отправлена на валидацию",
                        "schema": {
                            "$ref": "#/definitions/models.AddThemeResponse"
                        }
                    },
                    "400": {
                        "description": "Тема уже существует или некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/models.AddThemeResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/models.AddThemeResponse"
                        }
                    }
                }
            }
        },
        "/theme/{confirmation}": {
            "put": {
                "description": "Данный метод позволяет зарегистрировать/отклонить новую тему/метатему",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "theme"
                ],
                "summary": "Подтверждение/отклонение новой темы/метатемы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Подтверждение темы/метатемы (YES или NO)",
                        "name": "confirmation",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Предлагаемая тема",
                        "name": "theme",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmThemeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Тема успешно зарегистрирована",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmThemeResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные или тема уже существует",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmThemeResponse"
                        }
                    },
                    "422": {
                        "description": "Некорректные данные для подтверждения темы",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmThemeResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmThemeResponse"
                        }
                    }
                }
            }
        },
        "/user/authorize": {
            "post": {
                "description": "Позволяет авторизовать пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "Учетные данные пользователя",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthorizeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AuthorizeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.AuthorizeResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.AuthorizeResponse"
                        }
                    }
                }
            }
        },
        "/user/recovery": {
            "post": {
                "description": "Позволяет начать и завершить процесс восстановления пароля через email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Восстановление пароля",
                "parameters": [
                    {
                        "description": "Email пользователя или новый пароль",
                        "name": "recovery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешное восстановление пароля",
                        "schema": {
                            "$ref": "#/definitions/models.RecoverySuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryBadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Суффикс восстановления не найден",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryNotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "Время действия ссылки истекло",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryUnprocessableEntityResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryInternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/recovery/{recoverySuffix}": {
            "patch": {
                "description": "Позволяет начать и завершить процесс восстановления пароля через email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Восстановление пароля",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный суффикс восстановления",
                        "name": "recoverySuffix",
                        "in": "path"
                    },
                    {
                        "description": "Email пользователя или новый пароль",
                        "name": "recovery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешное восстановление пароля",
                        "schema": {
                            "$ref": "#/definitions/models.RecoverySuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryBadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Суффикс восстановления не найден",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryNotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "Время действия ссылки истекло",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryUnprocessableEntityResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/models.RecoveryInternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Позволяет зарегистрировать пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя для регистрации",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/blackList/{username}": {
            "put": {
                "description": "Позволяет добавить пользователя в черный список",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Добавление в черный список",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя, добавляющего в черный список",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Имя пользователя, добавляемого в черный список",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AddBlacklistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.AddBlacklistResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.AddBlacklistResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/friends": {
            "get": {
                "description": "Позволяет получить список друзей пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение списка друзей",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetFriendsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GetFriendsResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/models.GetFriendsResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/friends/{username}": {
            "post": {
                "description": "Позволяет отправить запрос дружбы от одного пользователя другому",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Отправление запроса дружбы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя, отправляющего запрос дружбы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Имя пользователя, получающего запрос дружбы",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SendFriendRequestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.SendFriendRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.SendFriendRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.SendFriendRequestResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Позволяет удалить из друзей пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Удаление из друзей",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя, удаляющего друга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Имя пользователя, удаляемого из списка друзей",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteFriendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteFriendResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteFriendResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/friends/{username}/{confirmation}": {
            "put": {
                "description": "Позволяет ответить на запрос дружбы от одного пользователя другому",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Подтверждение/отклонение запроса дружбы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя, принимающего запрос дружбы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Имя пользователя, отправившего запрос дружбы",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Подтверждение запроса дружбы (YES или NO)",
                        "name": "confirmation",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmFriendRequestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmFriendRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmFriendRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmFriendRequestResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/profile": {
            "get": {
                "description": "Позволяет получить информацию о пользователе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение информации профиля",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор профиля",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.GetProfileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.GetProfileResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GetProfileResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/models.GetProfileResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Позволяет изменить информацию о пользователе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Изменение информации профиля",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор профиля",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация профиля",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AddPlayerToRoomRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "john_doe"
                }
            }
        },
        "handlers.AddPlayerToRoomResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                },
                "room": {
                    "$ref": "#/definitions/handlers.Room"
                }
            }
        },
        "handlers.CreateRoomRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "Room One"
                }
            }
        },
        "handlers.CreateRoomResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                },
                "room": {
                    "$ref": "#/definitions/handlers.Room"
                }
            }
        },
        "handlers.Room": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        },
        "models.AddBlacklistResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.AddGameSearchRequest": {
            "type": "object",
            "required": [
                "metathemes"
            ],
            "properties": {
                "metathemes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.AddGameSearchResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.AddSpectatorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.AddThemeRequest": {
            "type": "object",
            "required": [
                "theme"
            ],
            "properties": {
                "theme": {
                    "$ref": "#/definitions/models.Theme"
                }
            }
        },
        "models.AddThemeResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.AuthorizeRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8,
                    "example": "securePassword123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "vasyaPupkin"
                }
            }
        },
        "models.AuthorizeResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.ConfirmFriendRequestResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.ConfirmThemeRequest": {
            "type": "object",
            "required": [
                "theme"
            ],
            "properties": {
                "metathemes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "theme": {
                    "$ref": "#/definitions/models.Theme"
                }
            }
        },
        "models.ConfirmThemeResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.DeleteFriendResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.Error": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer"
                },
                "errorDescription": {
                    "type": "string"
                }
            }
        },
        "models.Friend": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string",
                    "example": "4AAQSkZJRgABAQEAAAAAAADfjadFHADHda"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "username": {
                    "type": "string",
                    "example": "VasyaPupkin"
                }
            }
        },
        "models.GameSearch": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "metathemes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Theme"
                    }
                },
                "spectators": {
                    "description": "Добавленное поле для зрителей",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                },
                "status": {
                    "description": "\"searching\", \"found\", \"stopped\"",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.GetFriendsResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                },
                "friends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Friend"
                    }
                }
            }
        },
        "models.GetProfileResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "error": {
                    "$ref": "#/definitions/models.Error"
                },
                "image": {
                    "type": "string",
                    "example": "4AAQSkZJRgABAQEAAAAAAADfjadFHADHda"
                },
                "lastActivityDate": {
                    "type": "string",
                    "example": "2024-05-22T12:34:56Z"
                },
                "password": {
                    "type": "string",
                    "example": "hashedPassword123"
                },
                "registrationDate": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "ExampleUser"
                }
            }
        },
        "models.PlayersInRoomResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                },
                "room_id": {
                    "type": "string",
                    "example": "room123"
                }
            }
        },
        "models.RecoveryBadRequestError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer",
                    "example": 1
                },
                "errorDescription": {
                    "type": "string",
                    "example": "Аккаунт с указанным Email не существует"
                }
            }
        },
        "models.RecoveryBadRequestResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.RecoveryBadRequestError"
                }
            }
        },
        "models.RecoveryInternalServerError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer",
                    "example": 999
                },
                "errorDescription": {
                    "type": "string",
                    "example": "Внутренняя ошибка"
                }
            }
        },
        "models.RecoveryInternalServerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.RecoveryInternalServerError"
                }
            }
        },
        "models.RecoveryNotFoundError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer",
                    "example": 1
                },
                "errorDescription": {
                    "type": "string",
                    "example": "Уникальный суффикс восстановления не найден"
                }
            }
        },
        "models.RecoveryNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.RecoveryNotFoundError"
                }
            }
        },
        "models.RecoveryRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 256,
                    "example": "v.pupkin@g.nsu.ru"
                }
            }
        },
        "models.RecoverySuccessError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer",
                    "example": 0
                },
                "errorDescription": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "models.RecoverySuccessResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.RecoverySuccessError"
                }
            }
        },
        "models.RecoveryUnprocessableEntityError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer",
                    "example": 2
                },
                "errorDescription": {
                    "type": "string",
                    "example": "Время действия ссылки истекло, повторите процедуру"
                }
            }
        },
        "models.RecoveryUnprocessableEntityResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.RecoveryUnprocessableEntityError"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 256,
                    "example": "v.pupkin@g.nsu.ru"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8,
                    "example": "securePassword123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "vasyaPupkin"
                }
            }
        },
        "models.RegisterResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.SendFriendRequestResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.StopGameSearchResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.Theme": {
            "type": "object",
            "required": [
                "category",
                "name"
            ],
            "properties": {
                "category": {
                    "enum": [
                        "THEME",
                        "METATHEME"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ThemeCategory"
                        }
                    ]
                },
                "game_searches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GameSearch"
                    }
                },
                "id": {
                    "type": "string"
                },
                "metathemes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Theme"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "models.ThemeCategory": {
            "type": "string",
            "enum": [
                "THEME",
                "METATHEME"
            ],
            "x-enum-varnames": [
                "THEME",
                "METATHEME"
            ]
        },
        "models.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string",
                    "example": "TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCAuLi4="
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8,
                    "example": "newSecurePassword123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "vasyaPupkin"
                }
            }
        },
        "models.UpdateProfileResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "email",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 256
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "lastActivityDate": {
                    "type": "string"
                },
                "registrationDate": {
                    "type": "string"
                },
                "team": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 25
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "User Service API",
	Description:      "API сервис пользователей для взаимодействия с сервисом авторизации и сервисом игровых комнат",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
